default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: merm_dev

production:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: merm_db
  port: 5432
  database: merm_dev

test:
  <<: *default
  database: merm_test